# 0003_rename_video_upload_exercise_input_video_and_more.py
# Generated by Django 5.1.5 on 2025-01-26 15:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_exercise_angles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='video_upload',
            new_name='input_video',
        ),
        migrations.AddField(
            model_name='exercise',
            name='output_video',
            field=models.FileField(blank=True, null=True, upload_to='pose_videos'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='angles',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(blank=True, null=True),
                default=list,
                size=None
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='concentric_times',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(blank=True, null=True),
                default=list,
                size=None
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='eccentric_times',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(blank=True, null=True),
                default=list,
                size=None
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='forces',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(blank=True, null=True),
                default=list,
                size=None
            ),
            preserve_default=False,
        ),
    ]
