# Generated by Django 5.1.5 on 2025-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_chatbot_remove_user_gender_exercise_output_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlamaChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
