# Generated by Django 5.1.5 on 2025-02-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_llamachatbot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatbot',
        ),
        migrations.AddField(
            model_name='exercise',
            name='chatbot_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
