# Generated by Django 5.1.5 on 2025-02-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_delete_chatbot_exercise_chatbot_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
