# Generated by Django 5.1.5 on 2025-02-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_exercise_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepseekChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
